apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml 

images:
- name: python-app
  newName: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/pythonapp

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: python-app

- patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 3
  target:
    kind: HorizontalPodAutoscaler
    name: python-app-hpa

configMapGenerator:
- name: app-config
  literals:
  - DB_HOST=<PREPROD_RDS_ENDPOINT>
  - DB_SECRET_NAME=myapp/preprod/db/credentials
  - APP_ENV=preprod
